name: qlhanghoa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
      - assets/images/error.png
      - assets/images/success.png
      - assets/images/warning.png
      - assets/logo/logo_store_x2.png
      - assets/logo/logo_store.png
      - assets/logo/logo_thu_y_x2.png
      - assets/logo/logo_thu_y.png
      - assets/logo/logo_xanh_vang_x2.png
      - assets/logo/logo_xanh_vang.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
